### ISSUE TITLE
Users API not retrieving hourly rate

### ISSUE THREAD

**Issue by vizigin** [tick/tick-api#33]
Hi guys!

I need to retrieve hourly rate for users. How I can do that?

**Comment by johnlpollard** [comment]
Hey, I was looking at adding this. Haven't finished it yet. I will let you know once it's in production.

**Comment by johnlpollard** [comment]
@vizigin I just pushed this to production. Let me know if everything looks good for you!

**Comment by vizigin** [comment]
Thank you John

**Comment by vizigin** [comment]
@johnlpollard When I delete person in Users Tab, it delete billable_rate field

**Comment by johnlpollard** [comment]
Yes, that's because a user could have multiple subscriptions each with different billable rates. When you pull user info for your subscription, you are seeing his billable rate for your subscription. Remove him and he will no longer have a billable rate for your subscription (but still may have a billable rate with another subscription). Make sense?
